### ISSUE TITLE
SSL Error 60

### ISSUE THREAD

**Issue by squelch41** [SuperIlu/DOStodon#3]
Getting "Error 60" when try to log in saying SSL certificate on client or server cant be verified.

Using Pentium 3 with windows 98 dos.

Can see that is listed on Dec 13th issue on main page - using most recent clone of repo

Error:

[60] SSL peer certificate or SSH remote key was not OK at Curl.prototype. DoRequest (native)

at mstdn.js:66

at mstdn.js:146

at Login (login.js:42)

at Loop (dstdn.js:112)

DOJS ERROR

l

**Comment by ActionRetro** [comment]
I got the exact same error on Pentium 100, also Windows 98 DOS.

**Comment by SuperIlu** [comment]
Have you checked the system time? You need to have the current date in the RTC for it to work.
Which mastodon server are you using? I only checked SSL works against mastodon.social

**Comment by squelch41** [comment]
yes - have fallen foul of system time before with ssl :)
System time was correct.
Using retrochat.online

**Comment by SuperIlu** [comment]
I added test connections to several SSL/TLS sites in the current source of DOStodon and on DOSBox-X these work fine for me. I'll try on my AMD box...
```
Resolve(google.com) = [142,251,209,142]
Date/Time           = 2022-12-19T13:04:13.000Z
+++ Trying https://mastodon.social/about
+++ OK  https://mastodon.social/about
+++ Trying https://retrochat.online/about
+++ OK  https://retrochat.online/about
+++ Trying https://bitbang.social/about
+++ OK  https://bitbang.social/about
+++ Trying https://raw.githubusercontent.com/SuperIlu/DOjSHPackages/master/dojs/index.json
+++ OK  https://raw.githubusercontent.com/SuperIlu/DOjSHPackages/master/dojs/index.json
+++ Trying https://curl.se
+++ OK  https://curl.se
+++ Trying https://www.shdon.com/
+++ OK  https://www.shdon.com/
+++ Trying https://www.heise.de
+++ OK  https://www.heise.de
Logging in...Using CREDS.JSN
```

**Comment by SuperIlu** [comment]
I just downloaded the current version from https://github.com/SuperIlu/DOStodon/archive/refs/heads/main.zip and put it on my AMD K6-II 500 with 196MiB of RAM running FreeDOS and it works fine.
![WIN_20221219_13_29_26_Pro](https://user-images.githubusercontent.com/1155988/208426836-15ae7f15-1008-4ba4-a5e4-9a3747112e3a.jpg)

![WIN_20221219_13_29_31_Pro](https://user-images.githubusercontent.com/1155988/208426852-b48520aa-4f99-43fa-9437-811942b13fc4.jpg)

![WIN_20221219_13_29_35_Pro](https://user-images.githubusercontent.com/1155988/208426871-11150b42-7190-4188-be46-3005f2e3a7d9.jpg)

![WIN_20221219_13_30_19_Pro](https://user-images.githubusercontent.com/1155988/208426880-5a738ffb-c467-427b-87b7-ac65bb45ac62.jpg)

![WIN_20221219_13_30_24_Pro](https://user-images.githubusercontent.com/1155988/208426893-d839dfa2-5949-4fec-bfc9-09ddebb0813f.jpg)

![WIN_20221219_13_31_35_Pro](https://user-images.githubusercontent.com/1155988/208427149-e68007ea-855f-42c9-92b5-1a9623d348d7.jpg)

**Comment by squelch41** [comment]
mine seems to be working fine now on both my pentium 3 and 486 systems
