### ISSUE TITLE
Crashes on 486

### ISSUE THREAD

**Issue by squelch41** [SuperIlu/DOStodon#4]
On windows 98 dos, loading on 486 fails

(Presume due to needing i586 instructions so not really fixable?)

Shutting down Allegro

Exiting due to signal SIGABRT

Invalid Opcode at eip-0053aae0

eax-00000000 ebx-002d4d70 ecx=00000000 edx=00000000 esi 00000000 edi=00000000

ebp-00246200 esp-00244cac progran=C:\DOSTODONDOJS.EXE

cs: sel-00a4 base-00400000 limit=007affff

ds: sel=00ac base-00400000 limit=007affff es: sel=00ac base-00400000 limit=007affff

fs: sel-00ac base-00400000 limit=007affff

gs: sel-00bc base-00000000 limit=0010ffff ss: sel=00ac base-00400000 limit=007affff

App stack: [002deb20..0025eb201 Exceptn stack: [0025eacc..0025cb8c]

Call frame traceback EIPs:

0x0053aae0

**Comment by SuperIlu** [comment]
I don't own a 486, but I can try to reproduce on DOSBox...

**Comment by SuperIlu** [comment]
Also: how much RAM has the 486?

**Comment by squelch41** [comment]
> Also: how much RAM has the 486?

64mb

**Comment by SuperIlu** [comment]
can you give me some more specs on the machine?
CPU type/speed? graphics adapter? soundcard?

DOjS is compiled for 386, in theory it should work...

**Comment by squelch41** [comment]
yes of course-

V4P895P3 VLB Motherboard and AMD 486 133MHz CPU
64mb RAM, CF 4Gb HDD,
Realtek 8019 ethernet + XT-IDE bios ROM (isa), ES1869 soundcard (isa) , VLB multi-io card Cirrus Logic GD5428 1mb VGA
Win98 dos

realtek packet driver and mTCP tcp/ip stack
XTIDE rom in network card (to overcome bios limitations on hdd detection)

happy to give any more details needed/run test builds- let me know

**Comment by SuperIlu** [comment]
For now I can confirm that DOjS crashes on DOSBox w/ 486DX5-133 when I try TLS/SSL connections. Loading PNGs and JPGs works fine...
![image](https://user-images.githubusercontent.com/1155988/208457444-27482ec8-7407-4c7c-8bd6-d34f6af2b132.png)

**Comment by SuperIlu** [comment]
@squelch41 I pushed a new version that runs fine on DOSBox-X with an emulated 486.
The problem was mbedTLS which uses Pentium (or later) assembly instructions for AES acceleration. The code does noch check if the CPU actually supports these. Therefore I turned that feature off...

**Comment by squelch41** [comment]
yey! That works on my real 486!
