### ISSUE TITLE
DOSBox versions, per README

### ISSUE THREAD

**Issue by hxlnt** [SuperIlu/DOStodon#6]
Thanks for creating this project; I am looking forward to trying it!

In the README, the quickstart section notes that DOSBox-X is required, but a later section seems to contradict this:

> DO NOT use DOSBox-X right now

I'm running a standard DOSBox version from a year ago or so, I think, and am not too familiar with these different versions/forks. Some clarification on which DOSBox versions are supported would be appreciated!

**Comment by SuperIlu** [comment]
You are totally right.
I usually use DOSBox-X, but the MinGW-Windows version has some issues and that is why I recommend DOSBox-staging (see the end of the README).

Basically DOSBox-X and -staging add a lot of functions like networking, 3dfx and so on to the "plain" DOSBox.
The linked DOSBox-staging version and the example config is what I use for development of DOStodon (or at least I hope it still is) :)
